---
conditions: v1
dist: xenial
language: python

git:
  depth: 200

cache:
  pip: true

python:
- "3.7"

before_install:
- pip install tox-venv
install:
- tox --notest

script:
- tox

jobs:
  include:
  - python: "3.7"
    name: Checking pre-commit linter compliance
    env:
      TOXENV: pre-commit
  - python: "3.7"
    name: Checking docs build
    env:
      TOXENV: build-docs
  - &deploy-job
    stage: Upload a new version of python package to PYPI
    name: Publishing current Git tagged version of dist to PyPI
    if: repo == "sanitizers/octomachinery" AND tag IS present
    python: "3.7"
    env:
      TOXENV: build-dists
    before_deploy:
    - echo > setup.py
    deploy: &deploy-step
      provider: pypi
      on:
        all_branches: true
        tags: true
      user: octomachinery-bot
      password:
        secure: >-
          Q7r3VqzMsJst2lAN9rFVcqJAAx27pb/YUo4nK//+pCIRzRqQr8xRA5gCwT+Js5WCP2BFqR9mr1FjSX6WON3Q/oxnRpZrVN5bhYNvHFoEX4BZvJez26k2TxnudSD1yVnurv61oimxVgOP/WA/hvB4V+U2lkcsa/GK6sHhBoczUh78qgydl134dHYsKsES3PRfKTvYCYOT3gHMEO+aopd7P2M2+PazeqUKMGVM03S3IkiduhCtaD0txPQ7CDrsWnvAHyDiuRzjkewrEdUmumcWcISPMxwKYw5lp3+Jc1XK/GdTNAZVImMhsg/Uz5ZVU/8P+mStMtCvuKGPYksBaCzuHs6/C3+9L1LulL7loPiTyq5LKe8Jtoyv8Ze+3qlmbO1k4SvgfSLXPkCA4lqpHRXjX1InwaY3GsTI/bJZoKvE5LpANm6unS9AyZorzA8I5ZiT3A/D+pCtPV62PD90jvz987sEZh9IJuU5/koIYyHnpKbJT7IDI4voXIwYUEeK7WcwKbXFTf7lfushmk8YVL405KKYhQiQq6Z9pyNqEteNyqpvEKSnfn0CxwcDHyKpf7J5MCx/R9Y/y/NdVdYpFyQGUyNJ9h114kVcZi/x6j7voSAg0kRTWjaYrngH8yNCY0rYDd76PtEzdJDuq0nIXk8EcXeYEIsAbpHV1qHK0pU53ms=
      distributions:
      skip-cleanup: true
  - <<: *deploy-job
    name: >-
      Publishing current (unstable) Git revision of dist to Test PyPI
      on every commit
    if: >-  # Always run, except if PR or cron
      repo == "sanitizers/octomachinery" AND
      branch == "master" AND
      type == "push"
    deploy:
      <<: *deploy-step
      server: https://test.pypi.org/legacy/
      on:
        all_branches: true
